# Make sure that the additional_dependencies here match requirements.txt

ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi~=0.108.0
          - uvicorn[standard]~=0.25.0
          - jinja2~=3.1.2
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.281"
    hooks:
      - id: ruff
        additional_dependencies:
          - fastapi~=0.108.0
          - uvicorn[standard]~=0.25.0
          - jinja2~=3.1.2
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
